import initSqlJs from 'sql.js';
import type { Database, SqlJsStatic } from 'sql.js';
import wasmUrl from 'sql.js/dist/sql-wasm.wasm?url';
import schemaSql from '../../db/schema.sql?raw';
import seedSql from '../../db/seed.sql?raw';
import exercisesSql from '../../db/exercises.sql?raw';
import exerciseCategoriesSql from '../../db/exercise_categories.sql?raw';

export type DB = Database;

const PERSIST_KEY = 'hypertroph.db.v1';

// Schema/data migrations applied to existing (persisted) databases. Version 1 is
// the initial schema+seed; later versions are idempotent data/provenance fixes.
export const MIGRATIONS: { version: number; sql: string }[] = [
  {
    // Compliance/provenance fix: hand-authored demo foods & exercises were
    // mislabeled as third-party sources. Reassign them to the app-owned source
    // and drop the misleading source row / brand.
    version: 2,
    sql: `
      INSERT OR IGNORE INTO sources (id, name, license, license_url, attribution, redistribution, pack_version, retrieved_at)
      VALUES ('s_app','hypertroph+ original data','original-work',NULL,'Demo/seed data authored for hypertroph+ (not third-party).','allowed','base-model-1',1700000000000);
      UPDATE foods SET source_id = 's_app', data_quality = 'derived'
        WHERE source_id = 's_unlicense' OR (source_id = 's_usda' AND source_record_id LIKE 'seed-%');
      UPDATE exercises SET source_id = 's_app' WHERE source_id = 's_unlicense';
      UPDATE foods SET brand = NULL WHERE id = 'f_whey' AND brand = 'MyProtein';
      DELETE FROM sources WHERE id = 's_unlicense';
    `,
  },
  {
    // Add the public-domain Free Exercise DB catalogue (The Unlicense).
    // Generated by tools/import/import-exercises.mjs; idempotent.
    version: 3,
    sql: exercisesSql,
  },
  {
    // Allow user-defined meals. log_items.meal_section previously had a CHECK
    // limited to five fixed sections; rebuild the table without it. Existing
    // data (including child log_item_nutrients rows) is preserved verbatim.
    version: 4,
    sql: `
      CREATE TABLE log_items_new (
        id            TEXT PRIMARY KEY,
        local_date    TEXT NOT NULL REFERENCES log_days(local_date),
        meal_section  TEXT NOT NULL,
        food_id       TEXT REFERENCES foods(id),
        label         TEXT NOT NULL,
        quantity_g    REAL,
        portion_label TEXT,
        source_id     TEXT REFERENCES sources(id),
        created_at    INTEGER NOT NULL,
        updated_at    INTEGER NOT NULL,
        is_deleted    INTEGER NOT NULL DEFAULT 0 CHECK (is_deleted IN (0,1))
      );
      INSERT INTO log_items_new (id, local_date, meal_section, food_id, label, quantity_g, portion_label, source_id, created_at, updated_at, is_deleted)
        SELECT id, local_date, meal_section, food_id, label, quantity_g, portion_label, source_id, created_at, updated_at, is_deleted
        FROM log_items;
      DROP TABLE log_items;
      ALTER TABLE log_items_new RENAME TO log_items;
      CREATE INDEX IF NOT EXISTS idx_logitems_day ON log_items(local_date, meal_section);
    `,
  },
  {
    // Food taxonomy + body metrics.
    //
    // foods.category was a single free-text field and prep_state had a CHECK
    // limited to raw/cooked/as_sold/prepared/unknown. This rebuilds foods with
    // three independent normalization axes plus brand/product identity:
    //   - food_type_id   (normalized food taxonomy, from food_types)
    //   - entry_type     (generic / prepared / branded / custom)
    //   - prep_state     (widened: adds boiled/steamed/roasted/fried/baked/...)
    //   - manufacturer/product_variant/barcode/serving_description (branded)
    // Backfill comes only from real data that was already present (category
    // text of the app-authored seed, custom flag); everything else stays NULL.
    version: 5,
    sql: `
      CREATE TABLE IF NOT EXISTS food_types (
        id         TEXT PRIMARY KEY,
        name       TEXT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0
      );
      INSERT OR IGNORE INTO food_types (id, name, sort_order) VALUES
        ('grains','Grains & cereals',1),('legumes','Pulses & legumes',2),
        ('vegetables','Vegetables',3),('fruits','Fruits',4),
        ('dairy','Dairy',5),('eggs','Eggs',6),
        ('meat','Meat & poultry',7),('seafood','Seafood',8),
        ('oils','Oils & fats',9),('nuts','Nuts & seeds',10),
        ('snacks','Snacks & sweets',11),('beverages','Beverages',12),
        ('supplements','Supplements',13),('mixed_dishes','Mixed dishes',14),
        ('other','Other',99);

      CREATE TABLE foods_new (
        id                 TEXT PRIMARY KEY,
        canonical_name     TEXT NOT NULL,
        search_key         TEXT NOT NULL,
        brand              TEXT,
        category           TEXT,
        food_type_id       TEXT REFERENCES food_types(id),
        entry_type         TEXT CHECK (entry_type IN ('generic','prepared','branded','custom')),
        manufacturer       TEXT,
        product_variant    TEXT,
        barcode            TEXT,
        serving_description TEXT,
        prep_state         TEXT NOT NULL DEFAULT 'unknown'
                             CHECK (prep_state IN ('raw','cooked','boiled','steamed','roasted','fried','baked','dried','canned','frozen','as_sold','prepared','unknown')),
        basis              TEXT NOT NULL DEFAULT 'per_100g'
                             CHECK (basis IN ('per_100g','per_100ml')),
        language           TEXT,
        region             TEXT,
        source_id          TEXT NOT NULL REFERENCES sources(id),
        source_record_id   TEXT,
        data_quality       TEXT NOT NULL DEFAULT 'unverified'
                             CHECK (data_quality IN ('verified','derived','crowd','user','unverified')),
        is_custom          INTEGER NOT NULL DEFAULT 0 CHECK (is_custom IN (0,1)),
        is_recipe          INTEGER NOT NULL DEFAULT 0 CHECK (is_recipe IN (0,1)),
        is_deleted         INTEGER NOT NULL DEFAULT 0 CHECK (is_deleted IN (0,1)),
        published_at       TEXT,
        created_at         INTEGER NOT NULL,
        updated_at         INTEGER NOT NULL
      );
      INSERT INTO foods_new (id, canonical_name, search_key, brand, category, prep_state, basis, language, region, source_id, source_record_id, data_quality, is_custom, is_recipe, is_deleted, created_at, updated_at)
        SELECT id, canonical_name, search_key, brand, category, prep_state, basis, language, region, source_id, source_record_id, data_quality, is_custom, is_recipe, is_deleted, created_at, updated_at
        FROM foods;
      DROP TABLE foods;
      ALTER TABLE foods_new RENAME TO foods;
      CREATE INDEX IF NOT EXISTS idx_foods_name   ON foods(canonical_name);
      CREATE INDEX IF NOT EXISTS idx_foods_key    ON foods(search_key);
      CREATE INDEX IF NOT EXISTS idx_foods_custom ON foods(is_custom, is_deleted);
      CREATE INDEX IF NOT EXISTS idx_foods_type   ON foods(food_type_id);

      -- Backfill from real data only. App-authored seed category text maps to
      -- the normalized taxonomy; nothing is inferred for unlabeled rows.
      UPDATE foods SET food_type_id = CASE category
        WHEN 'grains' THEN 'grains' WHEN 'dairy' THEN 'dairy' WHEN 'fruit' THEN 'fruits'
        WHEN 'meat' THEN 'meat' WHEN 'fats' THEN 'oils' WHEN 'supplement' THEN 'supplements'
        ELSE food_type_id END
        WHERE category IN ('grains','dairy','fruit','meat','fats','supplement');
      UPDATE foods SET entry_type = 'custom' WHERE is_custom = 1 AND entry_type IS NULL;
      UPDATE foods SET entry_type = 'generic' WHERE source_id = 's_app' AND entry_type IS NULL;

      CREATE TABLE IF NOT EXISTS body_metrics (
        id          TEXT PRIMARY KEY,
        metric_type TEXT NOT NULL CHECK (metric_type IN ('weight_kg','height_cm','body_fat_pct','waist_cm','other')),
        value       REAL NOT NULL,
        local_date  TEXT NOT NULL,
        note        TEXT,
        created_at  INTEGER NOT NULL,
        updated_at  INTEGER NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_body_metrics_date ON body_metrics(metric_type, local_date);

      CREATE TABLE IF NOT EXISTS favorites (
        entity_type TEXT NOT NULL CHECK (entity_type IN ('food','exercise')),
        entity_id   TEXT NOT NULL,
        created_at  INTEGER NOT NULL,
        PRIMARY KEY (entity_type, entity_id)
      );

      CREATE TABLE IF NOT EXISTS recent_uses (
        entity_type  TEXT NOT NULL CHECK (entity_type IN ('food','exercise')),
        entity_id    TEXT NOT NULL,
        last_used_at INTEGER NOT NULL,
        PRIMARY KEY (entity_type, entity_id)
      );
    `,
  },
  {
    // Exercise taxonomy. The Free Exercise DB carries a `category` field
    // (strength/powerlifting/strongman/olympic weightlifting/cardio/stretching/
    // plyometrics) that the v3 importer previously discarded. This rebuilds the
    // exercises table to add category_id and applies the real assignments from
    // db/exercise_categories.sql (generated from the source catalogue).
    version: 6,
    sql: `
      CREATE TABLE IF NOT EXISTS exercise_categories (
        id   TEXT PRIMARY KEY,
        name TEXT NOT NULL
      );
      INSERT OR IGNORE INTO exercise_categories (id, name) VALUES
        ('resistance','Resistance'),('cardio','Cardio'),
        ('mobility','Mobility'),('stretching','Stretching'),('other','Other');

      CREATE TABLE exercises_new (
        id               TEXT PRIMARY KEY,
        canonical_name   TEXT NOT NULL,
        search_key       TEXT NOT NULL,
        source_id        TEXT NOT NULL REFERENCES sources(id),
        source_record_id TEXT,
        unilateral       INTEGER NOT NULL DEFAULT 0 CHECK (unilateral IN (0,1)),
        is_custom        INTEGER NOT NULL DEFAULT 0 CHECK (is_custom IN (0,1)),
        is_deleted       INTEGER NOT NULL DEFAULT 0 CHECK (is_deleted IN (0,1)),
        variation_group  TEXT,
        category_id      TEXT REFERENCES exercise_categories(id),
        created_at       INTEGER NOT NULL,
        updated_at       INTEGER NOT NULL
      );
      INSERT INTO exercises_new (id, canonical_name, search_key, source_id, source_record_id, unilateral, is_custom, is_deleted, variation_group, created_at, updated_at)
        SELECT id, canonical_name, search_key, source_id, source_record_id, unilateral, is_custom, is_deleted, variation_group, created_at, updated_at
        FROM exercises;
      DROP TABLE exercises;
      ALTER TABLE exercises_new RENAME TO exercises;
      CREATE INDEX IF NOT EXISTS idx_ex_name ON exercises(canonical_name);
      CREATE INDEX IF NOT EXISTS idx_ex_key  ON exercises(search_key);
      CREATE INDEX IF NOT EXISTS idx_ex_cat  ON exercises(category_id);

      ${exerciseCategoriesSql}

      -- App-authored seed exercises are resistance work; assign explicitly.
      UPDATE exercises SET category_id = 'resistance' WHERE id IN
        ('e_bench','e_incline_db','e_squat','e_deadlift','e_ohp','e_pullup','e_row','e_rdl','e_latraise');

      CREATE TABLE IF NOT EXISTS exercise_patterns (
        exercise_id TEXT NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
        pattern_id  TEXT NOT NULL REFERENCES movement_patterns(id),
        PRIMARY KEY (exercise_id, pattern_id)
      );
      INSERT OR IGNORE INTO movement_patterns (id, name) VALUES
        ('lunge','Lunge'),('carry','Carry');
      INSERT OR IGNORE INTO exercise_patterns (exercise_id, pattern_id) VALUES
        ('e_bench','horizontal_push'),('e_incline_db','horizontal_push'),
        ('e_squat','squat'),('e_rdl','hinge'),('e_deadlift','hinge'),
        ('e_ohp','vertical_push'),('e_pullup','vertical_pull'),('e_row','horizontal_pull');
    `,
  },
  {
    // User workout-plan templates. The `routines`/`routine_exercises` tables are
    // part of the base schema; this migration guarantees they exist on older
    // persisted databases and adds the per-exercise target prescription columns
    // to `workout_exercises` so a workout started from a plan can carry its
    // targets. Rebuild keeps existing workout/set history verbatim.
    version: 7,
    sql: `
      CREATE TABLE IF NOT EXISTS routines (
        id         TEXT PRIMARY KEY,
        name       TEXT NOT NULL,
        notes      TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        is_deleted INTEGER NOT NULL DEFAULT 0 CHECK (is_deleted IN (0,1))
      );
      CREATE TABLE IF NOT EXISTS routine_exercises (
        id          TEXT PRIMARY KEY,
        routine_id  TEXT NOT NULL REFERENCES routines(id) ON DELETE CASCADE,
        exercise_id TEXT NOT NULL REFERENCES exercises(id),
        target_sets INTEGER,
        target_reps TEXT,
        target_rir  INTEGER,
        rest_sec    INTEGER,
        seq         INTEGER NOT NULL DEFAULT 0
      );
      CREATE INDEX IF NOT EXISTS idx_routine_exercises ON routine_exercises(routine_id, seq);

      CREATE TABLE workout_exercises_new (
        id          TEXT PRIMARY KEY,
        workout_id  TEXT NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
        exercise_id TEXT NOT NULL REFERENCES exercises(id),
        seq         INTEGER NOT NULL DEFAULT 0,
        notes       TEXT,
        target_sets INTEGER,
        target_reps TEXT,
        target_rir  INTEGER
      );
      INSERT INTO workout_exercises_new (id, workout_id, exercise_id, seq, notes)
        SELECT id, workout_id, exercise_id, seq, notes FROM workout_exercises;
      DROP TABLE workout_exercises;
      ALTER TABLE workout_exercises_new RENAME TO workout_exercises;
      CREATE INDEX IF NOT EXISTS idx_we_workout ON workout_exercises(workout_id);
    `,
  },
];

function applyMigrations(db: DB): boolean {
  let current = 0;
  try {
    const stmt = db.prepare('SELECT MAX(version) AS v FROM schema_migrations');
    if (stmt.step()) {
      const row = stmt.getAsObject() as { v: number | null };
      current = row.v ?? 0;
    }
    stmt.free();
  } catch {
    return false;
  }
  if ((current ?? 0) >= Math.max(...MIGRATIONS.map((m) => m.version))) return false;
  // Some migrations rebuild tables (dropping parents with live FKs). Constraint
  // enforcement is re-checked afterwards via foreign_key_check.
  const fkOn = db.exec('PRAGMA foreign_keys')[0]?.values[0]?.[0] === 1;
  if (fkOn) db.run('PRAGMA foreign_keys = OFF');
  let changed = false;
  try {
    for (const m of MIGRATIONS) {
      if (m.version <= current) continue;
      db.run('BEGIN');
      try {
        db.run(m.sql);
        db.run('INSERT INTO schema_migrations (version, applied_at, checksum) VALUES (?, ?, ?)', [
          m.version,
          Date.now(),
          `compliance-v${m.version}`,
        ]);
        db.run('COMMIT');
        changed = true;
        current = m.version;
      } catch (e) {
        db.run('ROLLBACK');
        throw e;
      }
    }
  } finally {
    if (fkOn) {
      db.run('PRAGMA foreign_keys = ON');
      const violations = db.exec('PRAGMA foreign_key_check');
      if (violations.length) throw new Error('Migration left dangling foreign keys');
    }
  }
  return changed;
}

let sqlStatic: SqlJsStatic | null = null;

/** Shared sql.js runtime (WASM). Used by both the user DB and the reference DB. */
export async function getSqlStatic(): Promise<SqlJsStatic> {
  if (!sqlStatic) {
    sqlStatic = await initSqlJs({ locateFile: () => wasmUrl });
  }
  return sqlStatic;
}

function bytesToBase64(bytes: Uint8Array): string {
  let bin = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    bin += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(bin);
}

function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export function getStorage(): Storage | null {
  try {
    return typeof localStorage !== 'undefined' ? localStorage : null;
  } catch {
    return null;
  }
}

/**
 * Load the SQLite database. In the browser base model this uses sql.js (WASM)
 * with a localStorage persisted image. In the Tauri build, this function is
 * replaced by a rusqlite-backed implementation behind the same repository API.
 */
export async function loadDatabase(): Promise<DB> {
  const SQL = await getSqlStatic();

  const storage = getStorage();
  const stored = storage?.getItem(PERSIST_KEY);
  let db: DB;
  let fresh = false;

  if (stored) {
    db = new SQL.Database(base64ToBytes(stored));
  } else {
    db = new SQL.Database();
    db.run(schemaSql);
    db.run(seedSql);
    fresh = true;
  }

  db.run('PRAGMA foreign_keys = ON;');
  const migrated = applyMigrations(db);
  if (fresh || migrated) persist(db);
  return db;
}

export function persist(db: DB): void {
  const storage = getStorage();
  if (!storage) return;
  try {
    storage.setItem(PERSIST_KEY, bytesToBase64(db.export()));
  } catch {
    /* quota or unavailable storage - non-fatal for the base model */
  }
}

export function resetDatabase(): void {
  getStorage()?.removeItem(PERSIST_KEY);
}

export function exportDatabaseBytes(db: DB): Uint8Array {
  return db.export();
}
