import initSqlJs from 'sql.js';
import type { Database, SqlJsStatic } from 'sql.js';
import wasmUrl from 'sql.js/dist/sql-wasm.wasm?url';
import schemaSql from '../../db/schema.sql?raw';
import seedSql from '../../db/seed.sql?raw';
import exercisesSql from '../../db/exercises.sql?raw';

export type DB = Database;

const PERSIST_KEY = 'hypertroph.db.v1';

// Schema/data migrations applied to existing (persisted) databases. Version 1 is
// the initial schema+seed; later versions are idempotent data/provenance fixes.
export const MIGRATIONS: { version: number; sql: string }[] = [
  {
    // Compliance/provenance fix: hand-authored demo foods & exercises were
    // mislabeled as third-party sources. Reassign them to the app-owned source
    // and drop the misleading source row / brand.
    version: 2,
    sql: `
      INSERT OR IGNORE INTO sources (id, name, license, license_url, attribution, redistribution, pack_version, retrieved_at)
      VALUES ('s_app','hypertroph+ original data','original-work',NULL,'Demo/seed data authored for hypertroph+ (not third-party).','allowed','base-model-1',1700000000000);
      UPDATE foods SET source_id = 's_app', data_quality = 'derived'
        WHERE source_id = 's_unlicense' OR (source_id = 's_usda' AND source_record_id LIKE 'seed-%');
      UPDATE exercises SET source_id = 's_app' WHERE source_id = 's_unlicense';
      UPDATE foods SET brand = NULL WHERE id = 'f_whey' AND brand = 'MyProtein';
      DELETE FROM sources WHERE id = 's_unlicense';
    `,
  },
  {
    // Add the public-domain Free Exercise DB catalogue (The Unlicense).
    // Generated by tools/import/import-exercises.mjs; idempotent.
    version: 3,
    sql: exercisesSql,
  },
  {
    // Allow user-defined meals. log_items.meal_section previously had a CHECK
    // limited to five fixed sections; rebuild the table without it. Existing
    // data (including child log_item_nutrients rows) is preserved verbatim.
    version: 4,
    sql: `
      CREATE TABLE log_items_new (
        id            TEXT PRIMARY KEY,
        local_date    TEXT NOT NULL REFERENCES log_days(local_date),
        meal_section  TEXT NOT NULL,
        food_id       TEXT REFERENCES foods(id),
        label         TEXT NOT NULL,
        quantity_g    REAL,
        portion_label TEXT,
        source_id     TEXT REFERENCES sources(id),
        created_at    INTEGER NOT NULL,
        updated_at    INTEGER NOT NULL,
        is_deleted    INTEGER NOT NULL DEFAULT 0 CHECK (is_deleted IN (0,1))
      );
      INSERT INTO log_items_new (id, local_date, meal_section, food_id, label, quantity_g, portion_label, source_id, created_at, updated_at, is_deleted)
        SELECT id, local_date, meal_section, food_id, label, quantity_g, portion_label, source_id, created_at, updated_at, is_deleted
        FROM log_items;
      DROP TABLE log_items;
      ALTER TABLE log_items_new RENAME TO log_items;
      CREATE INDEX IF NOT EXISTS idx_logitems_day ON log_items(local_date, meal_section);
    `,
  },
];

function applyMigrations(db: DB): boolean {
  let current = 0;
  try {
    const stmt = db.prepare('SELECT MAX(version) AS v FROM schema_migrations');
    if (stmt.step()) {
      const row = stmt.getAsObject() as { v: number | null };
      current = row.v ?? 0;
    }
    stmt.free();
  } catch {
    return false;
  }
  if ((current ?? 0) >= Math.max(...MIGRATIONS.map((m) => m.version))) return false;
  // Some migrations rebuild tables (dropping parents with live FKs). Constraint
  // enforcement is re-checked afterwards via foreign_key_check.
  const fkOn = db.exec('PRAGMA foreign_keys')[0]?.values[0]?.[0] === 1;
  if (fkOn) db.run('PRAGMA foreign_keys = OFF');
  let changed = false;
  try {
    for (const m of MIGRATIONS) {
      if (m.version <= current) continue;
      db.run('BEGIN');
      try {
        db.run(m.sql);
        db.run('INSERT INTO schema_migrations (version, applied_at, checksum) VALUES (?, ?, ?)', [
          m.version,
          Date.now(),
          `compliance-v${m.version}`,
        ]);
        db.run('COMMIT');
        changed = true;
        current = m.version;
      } catch (e) {
        db.run('ROLLBACK');
        throw e;
      }
    }
  } finally {
    if (fkOn) {
      db.run('PRAGMA foreign_keys = ON');
      const violations = db.exec('PRAGMA foreign_key_check');
      if (violations.length) throw new Error('Migration left dangling foreign keys');
    }
  }
  return changed;
}

let sqlStatic: SqlJsStatic | null = null;

/** Shared sql.js runtime (WASM). Used by both the user DB and the reference DB. */
export async function getSqlStatic(): Promise<SqlJsStatic> {
  if (!sqlStatic) {
    sqlStatic = await initSqlJs({ locateFile: () => wasmUrl });
  }
  return sqlStatic;
}

function bytesToBase64(bytes: Uint8Array): string {
  let bin = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    bin += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(bin);
}

function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export function getStorage(): Storage | null {
  try {
    return typeof localStorage !== 'undefined' ? localStorage : null;
  } catch {
    return null;
  }
}

/**
 * Load the SQLite database. In the browser base model this uses sql.js (WASM)
 * with a localStorage persisted image. In the Tauri build, this function is
 * replaced by a rusqlite-backed implementation behind the same repository API.
 */
export async function loadDatabase(): Promise<DB> {
  const SQL = await getSqlStatic();

  const storage = getStorage();
  const stored = storage?.getItem(PERSIST_KEY);
  let db: DB;
  let fresh = false;

  if (stored) {
    db = new SQL.Database(base64ToBytes(stored));
  } else {
    db = new SQL.Database();
    db.run(schemaSql);
    db.run(seedSql);
    fresh = true;
  }

  db.run('PRAGMA foreign_keys = ON;');
  const migrated = applyMigrations(db);
  if (fresh || migrated) persist(db);
  return db;
}

export function persist(db: DB): void {
  const storage = getStorage();
  if (!storage) return;
  try {
    storage.setItem(PERSIST_KEY, bytesToBase64(db.export()));
  } catch {
    /* quota or unavailable storage - non-fatal for the base model */
  }
}

export function resetDatabase(): void {
  getStorage()?.removeItem(PERSIST_KEY);
}

export function exportDatabaseBytes(db: DB): Uint8Array {
  return db.export();
}
